import dotenv from 'dotenv';
dotenv.config();

export const CONFIG = {
  PORT: parseInt(process.env.PORT || '3001', 10),
  SUPABASE_URL: process.env.SUPABASE_URL || '',
  SUPABASE_KEY: process.env.SUPABASE_KEY || '',
  SUI_NETWORK: process.env.SUI_NETWORK || 'testnet',
  SUI_PACKAGE_ID: process.env.SUI_PACKAGE_ID || '0x50a536845980969dfa54c274f437f9da426e58b1ea5f1f38fe79ff29e8a684fd',
  PLATFORM_TREASURY: process.env.PLATFORM_TREASURY || '0xdbd3acbd6db16bdba55cf084ea36131bd97366e399859758689ab2dd686bcd60',
  WAGER_ACCEPT_TIMEOUT_MS: 30_000,
} as const;

export const GAME_CONSTANTS = {
  TURN_TIMER_MS: 60_000,
  MAX_LEVEL: 8,
  STAT_POINTS_PER_LEVEL: 3,
  STARTING_STAT_POINTS: 20,
  MIN_STAT: 3,
  LEVEL_HP: [0, 40, 65, 105, 170, 275, 445, 720, 1165] as readonly number[],
  LEVEL_WEAPON_DAMAGE: [0, 6, 8, 16, 20, 42, 52, 84, 136] as readonly number[],
  DAMAGE_RANGE_LOW: 0.8,
  DAMAGE_RANGE_HIGH: 1.2,
  STR_DAMAGE_BONUS: 0.5,
  DEX_DAMAGE_BONUS: 0.15,
  EVASION_PER_DEXTERITY: 0.5,
  EVASION_CAP: 30,
  CRIT_CHANCE_PER_INTUITION: 0.5,
  CRIT_CHANCE_CAP: 25,
  CRIT_MULTIPLIER_BASE: 1.5,
  CRIT_MULTIPLIER_PER_INTUITION: 0.01,
  DEFENSE_PER_ENDURANCE: 0.3,
  ANTI_CRIT_PER_ENDURANCE: 0.3,
  ANTI_EVASION_PER_STRENGTH: 0.3,
  CRIT_ARMOR_PEN: 0.5,
  DEFAULT_ATTACK_ZONES: 1,
  DEFAULT_BLOCK_ZONES: 2,
  SHIELD_BLOCK_ZONES: 3,
  DUAL_WIELD_ATTACK_ZONES: 2,
  DUAL_WIELD_BLOCK_ZONES: 1,
  SHIELD_BLOCK_LINES: [
    ['head', 'chest', 'stomach'],
    ['chest', 'stomach', 'belt'],
    ['stomach', 'belt', 'legs'],
    ['belt', 'legs', 'head'],
    ['legs', 'head', 'chest'],
  ] as readonly (readonly string[])[],
  BLOCK_LINES: [
    ['head', 'chest'],
    ['chest', 'stomach'],
    ['stomach', 'belt'],
    ['belt', 'legs'],
    ['legs', 'head'],
  ] as readonly (readonly string[])[],
  EQUIP_SLOTS_PER_LEVEL: [0, 1, 1, 2, 2, 3, 3, 4, 5] as readonly number[],
  LEVEL_XP: [0, 8, 21, 55, 144, 377, 987, 2584] as readonly number[],
  XP_WIN_MIN: 1,
  XP_WIN_MAX: 3,
  MATCHMAKING_INITIAL_RANGE: 200,
  MATCHMAKING_EXPAND_AMOUNT: 50,
  MATCHMAKING_EXPAND_INTERVAL_MS: 10_000,
  ELO_K_FACTOR: 32,
  ELO_MIN_RATING: 100,
  DEFAULT_RATING: 1000,
  CHAT_RATE_LIMIT_MS: 1000,
  STARTING_GOLD: 500,
  LOOT_NOTHING_CHANCE: 60,
  LOOT_COMMON_CHANCE: 25,
  LOOT_UNCOMMON_CHANCE: 10,
  LOOT_RARE_CHANCE: 4,
  LOOT_EPIC_CHANCE: 0.9,
  LOOT_LEGENDARY_CHANCE: 0.1,
  ZONES: ['head', 'chest', 'stomach', 'belt', 'legs'] as const,
} as const;
